### ISSUE TITLE
Error starting a game. Too many players on a selected map

### ISSUE THREAD

**Issue by ghost** [Gafaszt2/Dreams-of-Combustion#2]
Dear Gafaszt2, an odd issue is showing up whenever I try to run the game with your mod. After selecting the civ and pressing the button to start the game, a message of too many civs to play a map shows up. Even reducing the number of civs and or selecting a huge map...there is no way to play your mod. Any Civ, any map size and format.

![01](https://github.com/Gafaszt2/Dreams-of-Combustion/assets/161677901/62994fd5-cf68-4646-aeb9-a78ad1d8bff1)

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

java.lang.NullPointerException
	at com.unciv.logic.civilization.Civilization.getPreferredVictoryTypeObjects(Civilization.kt:371)
	at com.unciv.logic.civilization.Civilization.setTransients(Civilization.kt:721)
	at com.unciv.logic.GameInfo.setTransients(GameInfo.kt:650)
	at com.unciv.logic.GameStarter$startNewGame$7.invoke(GameStarter.kt:113)
	at com.unciv.logic.GameStarter$startNewGame$7.invoke(GameStarter.kt:105)
	at com.unciv.logic.GameStarter.runAndMeasure(GameStarter.kt:151)
	at com.unciv.logic.GameStarter.startNewGame(GameStarter.kt:105)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invokeSuspend(NewGameScreen.kt:304)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$startNewGame$2.invoke(NewGameScreen.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.startNewGame(NewGameScreen.kt:295)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen.access$startNewGame(NewGameScreen.kt:50)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invokeSuspend(NewGameScreen.kt:229)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invoke(NewGameScreen.kt)
	at com.unciv.ui.screens.newgamescreen.NewGameScreen$onStartGameClicked$7.invoke(NewGameScreen.kt)
	at com.unciv.utils.ConcurrencyKt$launchCrashHandling$1.invokeSuspend(Concurrency.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.utils.CrashHandlingDispatcher$dispatch$1.invoke(Concurrency.kt:173)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandling$1.invoke(CrashHandlingExtensions.kt:17)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.ui.crashhandling.CrashHandlingExtensionsKt$wrapCrashHandlingUnit$1.invoke(CrashHandlingExtensions.kt:33)
	at com.unciv.utils.CrashHandlingDispatcher.dispatch$lambda$0(Concurrency.kt:173)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Gafaszt2** [comment]
try disabling Atheism mod, maybe its that, i will look out how can i fix it

**Comment by Gafaszt2** [comment]
ok my friend, i just fixed it, now update your mod and you should be ready to go, enjoy Peru!

**Comment by ghost** [comment]
Gafaszt2, wonderful! Thanks for your prompt response and actions! I will try it asap! As soon as I arrive home I am going to update the mod and test it. Keep you posted! Thanks for sharing it! Best,
